/** Airport stations for daily-max weather markets. Coords = resolution airport, not city center. */
export type TempUnit = 'C' | 'F'
export type StationRegion = 'us' | 'eu' | 'asia' | 'latam' | 'oceania' | 'africa'

export type ResolutionSource = 'noaa' | 'wu' | 'hko'
export type RoundingMode = 'whole' | 'one_decimal'
export type PrimaryFetch =
  | 'synoptic_madis'
  | 'hko_daily_extract'
  | 'wu_daily_observations'

export interface Station {
  slug: string
  city: string
  icao: string
  stationName: string
  lat: number
  lon: number
  timezone: string
  unit: TempUnit
  biasC: number
  peakHour: number
  region: StationRegion
  /** When false, do not lock YES on METAR print (HK Observatory ≠ VHHH). */
  metarIsResolution?: boolean
  note?: string
  /** Polymarket resolution feed (NOAA WRH / WU / HKO). */
  resolutionSource?: ResolutionSource
  resolutionStationId?: string
  officialUrl?: string
  rounding?: RoundingMode
  primaryFetch?: PrimaryFetch
  climateClass?: string
  /** True for WU/HKO — METAR must not authorize lock-YES. */
  sourceRisk?: boolean
}

export const STATIONS: Station[] = [
  {
    "slug": "nyc",
    "city": "NYC",
    "icao": "KLGA",
    "stationName": "LaGuardia",
    "lat": 40.7772,
    "lon": -73.8726,
    "timezone": "America/New_York",
    "unit": "F",
    "biasC": -0.4,
    "peakHour": 15,
    "region": "us",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "KLGA",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=klga",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "US_F",
    "note": "LaGuardia KLGA, not JFK/EWR/Central Park. US NOAA uses Show Hourly Data Temp column."
  },
  {
    "slug": "london",
    "city": "London",
    "icao": "EGLC",
    "stationName": "London City",
    "lat": 51.5053,
    "lon": 0.0553,
    "timezone": "Europe/London",
    "unit": "C",
    "biasC": -0.3,
    "peakHour": 15,
    "region": "eu",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "EGLC",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=eglc",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_europe",
    "note": "London City EGLC, not Heathrow EGLL."
  },
  {
    "slug": "paris",
    "city": "Paris",
    "icao": "LFPB",
    "stationName": "Le Bourget",
    "lat": 48.9694,
    "lon": 2.4414,
    "timezone": "Europe/Paris",
    "unit": "C",
    "biasC": -0.6,
    "peakHour": 15,
    "region": "eu",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "LFPB",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=lfpb",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_europe",
    "note": "Le Bourget LFPB, not CDG LFPG."
  },
  {
    "slug": "tokyo",
    "city": "Tokyo",
    "icao": "RJTT",
    "stationName": "Haneda",
    "lat": 35.5523,
    "lon": 139.7798,
    "timezone": "Asia/Tokyo",
    "unit": "C",
    "biasC": -0.2,
    "peakHour": 14,
    "region": "asia",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "RJTT",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=rjtt",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_asia",
    "note": "Haneda RJTT, not Narita RJAA."
  },
  {
    "slug": "hong-kong",
    "city": "Hong Kong",
    "icao": "VHHH",
    "stationName": "HK Observatory",
    "lat": 22.3022,
    "lon": 114.1743,
    "timezone": "Asia/Hong_Kong",
    "unit": "C",
    "biasC": 0.8,
    "peakHour": 14,
    "region": "asia",
    "metarIsResolution": false,
    "resolutionSource": "hko",
    "resolutionStationId": "HKO",
    "officialUrl": "https://www.weather.gov.hk/en/cis/climat.htm",
    "rounding": "one_decimal",
    "primaryFetch": "hko_daily_extract",
    "climateClass": "C_asia",
    "sourceRisk": true,
    "note": "HKO Absolute Daily Max (deg. C) to one decimal from Daily Extract. VHHH METAR is NOT the official thermometer \u2014 disable METAR lock rules. Fallback void\u2192lowest bracket after 7 days ET."
  },
  {
    "slug": "shanghai",
    "city": "Shanghai",
    "icao": "ZSPD",
    "stationName": "Pudong",
    "lat": 31.1434,
    "lon": 121.8052,
    "timezone": "Asia/Shanghai",
    "unit": "C",
    "biasC": -0.3,
    "peakHour": 14,
    "region": "asia",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "ZSPD",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=zspd",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_asia"
  },
  {
    "slug": "miami",
    "city": "Miami",
    "icao": "KMIA",
    "stationName": "Miami Intl",
    "lat": 25.7959,
    "lon": -80.287,
    "timezone": "America/New_York",
    "unit": "F",
    "biasC": -0.2,
    "peakHour": 14,
    "region": "us",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "KMIA",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=kmia",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "US_F"
  },
  {
    "slug": "chicago",
    "city": "Chicago",
    "icao": "KORD",
    "stationName": "O'Hare Intl",
    "lat": 41.96017,
    "lon": -87.93161,
    "timezone": "America/Chicago",
    "unit": "F",
    "biasC": -0.3,
    "peakHour": 15,
    "region": "us",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "KORD",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=kord",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "US_F",
    "note": "Chicago O'Hare Intl (KORD) \u2014 Gamma resolution station, not Midway."
  },
  {
    "slug": "los-angeles",
    "city": "Los Angeles",
    "icao": "KLAX",
    "stationName": "LAX",
    "lat": 33.9416,
    "lon": -118.4085,
    "timezone": "America/Los_Angeles",
    "unit": "F",
    "biasC": -0.8,
    "peakHour": 14,
    "region": "us",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "KLAX",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=klax",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "US_F"
  },
  {
    "slug": "atlanta",
    "city": "Atlanta",
    "icao": "KATL",
    "stationName": "Hartsfield",
    "lat": 33.6407,
    "lon": -84.4277,
    "timezone": "America/New_York",
    "unit": "F",
    "biasC": -0.2,
    "peakHour": 15,
    "region": "us",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "KATL",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=katl",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "US_F"
  },
  {
    "slug": "dallas",
    "city": "Dallas",
    "icao": "KDAL",
    "stationName": "Love Field",
    "lat": 32.83836,
    "lon": -96.83584,
    "timezone": "America/Chicago",
    "unit": "F",
    "biasC": -0.2,
    "peakHour": 16,
    "region": "us",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "KDAL",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=kdal",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "US_F",
    "note": "Dallas Love Field (KDAL) \u2014 Gamma resolution station, not DFW."
  },
  {
    "slug": "seoul",
    "city": "Seoul",
    "icao": "RKSI",
    "stationName": "Incheon",
    "lat": 37.4602,
    "lon": 126.4407,
    "timezone": "Asia/Seoul",
    "unit": "C",
    "biasC": -0.5,
    "peakHour": 14,
    "region": "asia",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "RKSI",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=rksi",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_asia",
    "note": "Title is Seoul (Incheon). Incheon RKSI, not Gimpo RKSS."
  },
  {
    "slug": "taipei",
    "city": "Taipei",
    "icao": "RCSS",
    "stationName": "Songshan",
    "lat": 25.0694,
    "lon": 121.5519,
    "timezone": "Asia/Taipei",
    "unit": "C",
    "biasC": 0.2,
    "peakHour": 14,
    "region": "asia",
    "metarIsResolution": false,
    "resolutionSource": "wu",
    "resolutionStationId": "RCSS",
    "officialUrl": "https://www.wunderground.com/history/daily/tw/taipei/RCSS",
    "rounding": "whole",
    "primaryFetch": "wu_daily_observations",
    "climateClass": "C_asia",
    "sourceRisk": true,
    "note": "WU primary: Daily Observations table (NOT Day High & Low summary). Songshan RCSS not Taoyuan RCTP. METAR useful for race but not lock-authoritative vs WU. source_risk."
  },
  {
    "slug": "singapore",
    "city": "Singapore",
    "icao": "WSSS",
    "stationName": "Changi",
    "lat": 1.3644,
    "lon": 103.9915,
    "timezone": "Asia/Singapore",
    "unit": "C",
    "biasC": -0.2,
    "peakHour": 14,
    "region": "asia",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "WSSS",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=wsss",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_asia",
    "note": "Tropics/monsoon class \u2014 rain can end heating early."
  },
  {
    "slug": "munich",
    "city": "Munich",
    "icao": "EDDM",
    "stationName": "Munich Airport",
    "lat": 48.3538,
    "lon": 11.7861,
    "timezone": "Europe/Berlin",
    "unit": "C",
    "biasC": -0.4,
    "peakHour": 15,
    "region": "eu",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "EDDM",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=eddm",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_continental"
  },
  {
    "slug": "madrid",
    "city": "Madrid",
    "icao": "LEMD",
    "stationName": "Barajas",
    "lat": 40.4983,
    "lon": -3.5676,
    "timezone": "Europe/Madrid",
    "unit": "C",
    "biasC": -0.3,
    "peakHour": 16,
    "region": "eu",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "LEMD",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=lemd",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_med"
  },
  {
    "slug": "ankara",
    "city": "Ankara",
    "icao": "LTAC",
    "stationName": "Esenboga",
    "lat": 40.1281,
    "lon": 32.9951,
    "timezone": "Europe/Istanbul",
    "unit": "C",
    "biasC": -0.2,
    "peakHour": 15,
    "region": "eu",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "LTAC",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=ltac",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_med"
  },
  {
    "slug": "wellington",
    "city": "Wellington",
    "icao": "NZWN",
    "stationName": "Wellington Airport",
    "lat": -41.3272,
    "lon": 174.8053,
    "timezone": "Pacific/Auckland",
    "unit": "C",
    "biasC": -0.6,
    "peakHour": 14,
    "region": "oceania",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "NZWN",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=nzwn",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_oceania"
  },
  {
    "slug": "buenos-aires",
    "city": "Buenos Aires",
    "icao": "SAEZ",
    "stationName": "Ezeiza",
    "lat": -34.8222,
    "lon": -58.5358,
    "timezone": "America/Argentina/Buenos_Aires",
    "unit": "C",
    "biasC": -0.4,
    "peakHour": 15,
    "region": "latam",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "SAEZ",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=saez",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_latam"
  },
  {
    "slug": "sao-paulo",
    "city": "Sao Paulo",
    "icao": "SBGR",
    "stationName": "Guarulhos",
    "lat": -23.4356,
    "lon": -46.4731,
    "timezone": "America/Sao_Paulo",
    "unit": "C",
    "biasC": -0.3,
    "peakHour": 15,
    "region": "latam",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "SBGR",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=sbgr",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_latam"
  },
  {
    "slug": "toronto",
    "city": "Toronto",
    "icao": "CYYZ",
    "stationName": "Pearson",
    "lat": 43.6777,
    "lon": -79.6248,
    "timezone": "America/Toronto",
    "unit": "C",
    "biasC": -0.3,
    "peakHour": 15,
    "region": "us",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "CYYZ",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=cyyz",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_north_america_C",
    "note": "Canada \u00b0C (not US_F)."
  },
  {
    "slug": "beijing",
    "city": "Beijing",
    "icao": "ZBAA",
    "stationName": "Capital",
    "lat": 40.0799,
    "lon": 116.6031,
    "timezone": "Asia/Shanghai",
    "unit": "C",
    "biasC": -0.2,
    "peakHour": 15,
    "region": "asia",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "ZBAA",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=zbaa",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_asia"
  },
  {
    "slug": "wuhan",
    "city": "Wuhan",
    "icao": "ZHHH",
    "stationName": "Tianhe",
    "lat": 30.7838,
    "lon": 114.2081,
    "timezone": "Asia/Shanghai",
    "unit": "C",
    "biasC": -0.2,
    "peakHour": 15,
    "region": "asia",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "ZHHH",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=zhhh",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_asia"
  },
  {
    "slug": "busan",
    "city": "Busan",
    "icao": "RKPK",
    "stationName": "Gimhae",
    "lat": 35.1796,
    "lon": 128.9382,
    "timezone": "Asia/Seoul",
    "unit": "C",
    "biasC": -0.3,
    "peakHour": 14,
    "region": "asia",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "RKPK",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=rkpk",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_asia"
  },
  {
    "slug": "seattle",
    "city": "Seattle",
    "icao": "KSEA",
    "stationName": "Sea-Tac",
    "lat": 47.4502,
    "lon": -122.3088,
    "timezone": "America/Los_Angeles",
    "unit": "F",
    "biasC": -0.4,
    "peakHour": 16,
    "region": "us",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "KSEA",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=ksea",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "US_F"
  },
  {
    "slug": "denver",
    "city": "Denver",
    "icao": "KBKF",
    "stationName": "Buckley SFB",
    "lat": 39.713,
    "lon": -104.758,
    "timezone": "America/Denver",
    "unit": "F",
    "biasC": -0.3,
    "peakHour": 15,
    "region": "us",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "KBKF",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=kbkf",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "US_F",
    "note": "Buckley SFB (KBKF) \u2014 Gamma resolution station, not Denver Intl."
  },
  {
    "slug": "istanbul",
    "city": "Istanbul",
    "icao": "LTFM",
    "stationName": "Istanbul Airport",
    "lat": 41.2753,
    "lon": 28.7519,
    "timezone": "Europe/Istanbul",
    "unit": "C",
    "biasC": -0.4,
    "peakHour": 15,
    "region": "eu",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "LTFM",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=LTFM",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_med",
    "note": "NOAA WRH (not WU). Same Synoptic path as Lucknow."
  },
  {
    "slug": "mexico-city",
    "city": "Mexico City",
    "icao": "MMMX",
    "stationName": "Benito Juarez",
    "lat": 19.4363,
    "lon": -99.0721,
    "timezone": "America/Mexico_City",
    "unit": "C",
    "biasC": -0.3,
    "peakHour": 15,
    "region": "latam",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "MMMX",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=mmmx",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_latam"
  },
  {
    "slug": "cape-town",
    "city": "Cape Town",
    "icao": "FACT",
    "stationName": "Cape Town Intl",
    "lat": -33.9648,
    "lon": 18.6017,
    "timezone": "Africa/Johannesburg",
    "unit": "C",
    "biasC": -0.3,
    "peakHour": 14,
    "region": "africa",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "FACT",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=fact",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_africa"
  },
  {
    "slug": "milan",
    "city": "Milan",
    "icao": "LIMC",
    "stationName": "Malpensa",
    "lat": 45.631,
    "lon": 8.728,
    "timezone": "Europe/Rome",
    "unit": "C",
    "biasC": -0.3,
    "peakHour": 15,
    "region": "eu",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "LIMC",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=limc",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_med",
    "note": "Milan Malpensa (LIMC) \u2014 Gamma resolution station, not Linate."
  },
  {
    "slug": "amsterdam",
    "city": "Amsterdam",
    "icao": "EHAM",
    "stationName": "Schiphol",
    "lat": 52.3105,
    "lon": 4.7683,
    "timezone": "Europe/Amsterdam",
    "unit": "C",
    "biasC": -0.4,
    "peakHour": 15,
    "region": "eu",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "EHAM",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=eham",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_europe"
  },
  {
    "slug": "warsaw",
    "city": "Warsaw",
    "icao": "EPWA",
    "stationName": "Chopin",
    "lat": 52.1657,
    "lon": 20.9671,
    "timezone": "Europe/Warsaw",
    "unit": "C",
    "biasC": -0.3,
    "peakHour": 15,
    "region": "eu",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "EPWA",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=epwa",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_continental"
  },
  {
    "slug": "shenzhen",
    "city": "Shenzhen",
    "icao": "ZGSZ",
    "stationName": "Bao'an",
    "lat": 22.6394,
    "lon": 113.8108,
    "timezone": "Asia/Shanghai",
    "unit": "C",
    "biasC": -0.2,
    "peakHour": 14,
    "region": "asia",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "ZGSZ",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=zgsz",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_asia"
  },
  {
    "slug": "chengdu",
    "city": "Chengdu",
    "icao": "ZUUU",
    "stationName": "Shuangliu",
    "lat": 30.5785,
    "lon": 103.947,
    "timezone": "Asia/Shanghai",
    "unit": "C",
    "biasC": -0.2,
    "peakHour": 15,
    "region": "asia",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "ZUUU",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=zuuu",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_asia"
  },
  {
    "slug": "kuala-lumpur",
    "city": "Kuala Lumpur",
    "icao": "WMKK",
    "stationName": "KLIA",
    "lat": 2.7456,
    "lon": 101.7099,
    "timezone": "Asia/Kuala_Lumpur",
    "unit": "C",
    "biasC": -0.2,
    "peakHour": 14,
    "region": "asia",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "WMKK",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=wmkk",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_asia",
    "note": "Tropics/monsoon."
  },
  {
    "slug": "lucknow",
    "city": "Lucknow",
    "icao": "VILK",
    "stationName": "Chaudhary Charan Singh",
    "lat": 26.7606,
    "lon": 80.8893,
    "timezone": "Asia/Kolkata",
    "unit": "C",
    "biasC": -0.2,
    "peakHour": 15,
    "region": "asia",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "VILK",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=vilk",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_asia",
    "note": "Canonical Synoptic/MADIS path documented in lucknow-wx README. api.weather.gov empty for VILK."
  },
  {
    "slug": "seoul-incheon",
    "city": "Seoul",
    "icao": "RKSI",
    "stationName": "Incheon",
    "lat": 37.4602,
    "lon": 126.4407,
    "timezone": "Asia/Seoul",
    "unit": "C",
    "biasC": -0.5,
    "peakHour": 14,
    "region": "asia",
    "metarIsResolution": true,
    "resolutionSource": "noaa",
    "resolutionStationId": "RKSI",
    "officialUrl": "https://www.weather.gov/wrh/timeseries?site=rksi",
    "rounding": "whole",
    "primaryFetch": "synoptic_madis",
    "climateClass": "C_asia",
    "note": "Duplicate of seoul slug \u2192 same Gamma series Seoul (Incheon)."
  }
]

export const STATIONS_BY_SLUG: Record<string, Station> = Object.fromEntries(
  STATIONS.map((s) => [s.slug, s]),
)

export const STATIONS_BY_ICAO: Record<string, Station> = Object.fromEntries(
  STATIONS.map((s) => [s.icao, s]),
)

export function findStationByCityHint(hint: string): Station | undefined {
  const h = hint
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
  if (STATIONS_BY_SLUG[h]) return STATIONS_BY_SLUG[h]
  return STATIONS.find(
    (s) =>
      s.slug === h ||
      s.city.toLowerCase() === hint.toLowerCase() ||
      s.slug.includes(h) ||
      h.includes(s.slug),
  )
}

export function stationResolutionId(station: Station): string {
  return (station.resolutionStationId || station.icao).toUpperCase()
}

export function stationSourceRisk(station: Station): boolean {
  if (station.sourceRisk) return true
  if (station.metarIsResolution === false) return true
  const src = station.resolutionSource
  return src === 'wu' || src === 'hko'
}

